name: Website System | Feature Request
description: Suggest an idea for the website itself (Not the documentation!)
title: "[Site | Feature] You Title Here"
labels: ["enhancement", "for-website"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! By taking this form, you're asking for a new feature, improvement or other requests to the website. If you're looking to report a bug, or ask for a documentation issue, please use the appropriate template.
  - type: textarea
    id: why
    attributes:
      label: Related Problem (optional)
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: The Feature
      description: What's the feature you'd like to be added? Describe the solution you'd like.
      placeholder: A clear and concise description of what you wanna happen
    validations:
      required: true
  - type: textarea
    id: others
    attributes:
      label: Additional Notes (optional)
      description: Is there anything else you'd like to tell us?
    validations:
      required: false
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't [already an issue](https://github.com/iNKORE-NET/Documentation/issues) that reports the same issue to avoid creating a duplicate.
          required: true
        - label: Make sure that the issue is a request of the website itself and not the documentation. If you're looking to report a bug or a documentation issue, please use the appropriate template.
          required: true
        - label: Check that this is a request that is a feature or something we can take action on. If you're looking to ask for help or support, open a [GitHub Discussion](https://github.com/iNKORE-NET/Documentation/discussions) or join [our community](https://inkore.net/about#social).
          required: true
        - label: I know that we can't guarantee that we will satisfy your request. This is not reall our duty to do everything anyone asks for. Also, I will treat our staff, contributors, and other users with respect and kindness.
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details (optional)
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false


  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
