name: Document Content | Bug Report
description: There's a problem in the document content. (Not the website system!)
title: "[Docs | Bug] You Title Here"
labels: ["bug", "for-document"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! By taking this form, you're sure that the issue is related to the document content itself and not the website system. If you're looking to ask for a feature or report a website bug, please use the appropriate template.
  - type: textarea
    id: what-happened
    attributes:
      label: The Annoying Bug
      description: What happened? Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: location
    attributes:
      label: Location(s)
      description: Where did you find the bug? Please provide the URL(s) of the page(s) where the bug is located.
      placeholder: https://docs.inkore.net/path/to/page
      value: https://docs.inkore.net/
    validations:
      required: true
  - type: dropdown
    id: is-localized
    attributes:
      label: Localization
      description: Does the bug only occur in specific languages, or is it present in all languages?
      options:
        - Only in specific languages (Please tell us which languages in the next field)
        - In all languages
    validations:
      required: true
  - type: textarea
    id: others
    attributes:
      label: Additional Notes (optional)
      description: Is there anything else you'd like to tell us? If you choose `Others` in the browser or system field, please specify here.
    validations:
      required: false
  - type: dropdown
    id: will-contribute
    attributes:
      label: Contribution
      description: Are you willing to contribute to fixing the bug by submitting a pull request? If you are, we may help guide you through the process, you'll be credited for your contribution, and you can open a pull request whenever you're ready.
      options:
        - Yes, I will contribute
        - No, I can't contribute
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't [already an issue](https://github.com/iNKORE-NET/Documentation/issues) that reports the same issue to avoid creating a duplicate.
          required: true
        - label: Make sure that the issue is related to bugs of the documentation content itself and not the website system. If you're looking to ask for a feature or report a website issue, please use the appropriate template.
          required: true
        - label: Check that this is a concrete bug. If you're looking to ask for help or support, open a [GitHub Discussion](https://github.com/iNKORE-NET/Documentation/discussions) or join [our community](https://inkore.net/about#social).
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details (optional)
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
