name: Website System | Bug Report
description: There's someting wrong with the website itself (Not the documentation!).
title: "[Site | Bug] You Title Here"
labels: ["bug", "for-website"]

# projects: ["octo-org/1", "octo-org/44"]
# assignees:
#   - 

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! By taking this form, you're sure that the issue is related to bugs of the website itself and not the documentation. If you're looking to ask for a feature or report a documentation issue, please use the appropriate template.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: checkboxes
    id: latest
    attributes:
      label: At the time you file this issue, is it still happening after using Shift+F5 or clearing the cache?
      description: If not, please update and check if the issue persists.
      required: true

  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
