name: Website System | Bug Report
description: There's someting wrong with the website itself (Not the documentation!).
title: "[Site | Bug] You Title Here"
labels: ["bug", "for-website"]

# projects: ["octo-org/1", "octo-org/44"]
# assignees:
#   - 

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! By taking this form, you're sure that the issue is related to bugs of the website itself and not the documentation. If you're looking to ask for a feature or report a documentation issue, please use the appropriate template.
  - type: textarea
    id: what-happened
    attributes:
      label: The Annoying Bug
      description: What happened? Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: How can we reproduce the bug? Please provide the steps to reproduce the bug.
      placeholder: |
        1. 
        2. 
        3.
        ..
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Browser
      description: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Others 
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: System
      description: Which operating system are you using to reproduce the bug?
      multiple: true
      options:
        - Windows 11
        - Windows 10
        - Windows 8/8.1
        - Windows 7
        - Windows 7 or older
        - OS X
        - Ubuntu
        - Fedora
        - Debian
        - CentOS
        - Android
        - iOS
        - Others (Specify in the additional notes)
    validations:
      required: true
  - type: textarea
    id: others
    attributes:
      label: Additional Notes
      description: Is there anything else you'd like to tell us? If you choose `Others` in the browser or system field, please specify here.
    validations:
      required: false
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Check that there isn't [already an issue](https://github.com/iNKORE-NET/Documentation/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Make sure that the issue is related to bugs of the website itself and not the documentation. If you're looking to ask for a feature or report a documentation issue, please use the appropriate template.
          required: true
        - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/iNKORE-NET/Documentation/discussions) or join [our community](https://inkore.net/about#social).
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false


  # - type: checkboxes
  #   id: terms
  #   attributes:
  #     label: Code of Conduct
  #     description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
  #     options:
  #       - label: I agree to follow this project's Code of Conduct
  #         required: true
